# --- Catppuccin Latte (Light Mode) ---
set -g status-style bg='#eff1f5',fg='#4c4f69'

# Left side - Session & Prefix Indicator
set -g status-left-length 30
set -g status-left "#{?client_prefix,#[bg=#df8e1d]#[fg=#eff1f5],#[fg=#40a02b]} bold ❐ #S #[          default] "

# Middle - Window List
set -g window-status-format '#[fg=#7c7f93] #I:#W#{?window_zoomed_flag, 󰁌 ,} '
set -g window-status-current-format '#[fg=#fe640b,bold,bg=#ccd0da] #I:#W#{?window_zoomed_flag, 󰁌 ,} '

# Right side - RAM, Date & Time
set -g status-right-length 100
set -g status-right "#[fg=#1e66f5] RAM: #(memory_pressure | awk '/System-wide memory free percentage/ { printf \"%%d%%%%\", 100-$5 }') #[fg=#8839ef] %Y-%m-%d #[fg=#ea76cb] %H:%M "

# Pane Borders
set -g pane-border-style fg='#bcc0cc'
set -g pane-active-border-style fg='#1e66f5'
