set -g status-style bg='#1e1e2e',fg='#cdd6f4'
set -g status-left '#[fg='#a6e3a1',bold] ❐ #S '
set -g window-status-format '#[fg='#6c7086'] #I:#W '
set -g window-status-current-format '#[fg='#fab387',bold,bg='#313244'] #I:#W '
set -g status-right '#[fg='#89b4fa'] %Y-%m-%d #[fg='#f5c2e7'] %H:%M '
set -g pane-border-style fg='#313244'
set -g pane-active-border-style fg='#89b4fa'
